[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
allow_paths = ["../node_modules"]
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
ffi = true
via_ir = true

remappings = [
  "@openzeppelin/=src/vendor/openzeppelin/",
  "@openzeppelin-contracts/=../node_modules/@openzeppelin/contracts/"
]
